### PR TITLE
Update formula to v0.17.1

### PR DESCRIPTION
**Pull request by ni4**

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Thanks @ni4 ! There seems to be a failure to build on Apple on macOS 14 according to GitHub, but we can fix it later.

**Comment by ni4** [comment]
> Thanks @ni4 ! There seems to be a failure to build on Apple on macOS 14 according to GitHub, but we can fix it later.

Errm, where do you see it? Probably I'm missing something. I could try to reproduce that in Parallels (as I'm on 13.x) once this is merged.

**Review by maxirmx — CHANGES_REQUESTED** [review]
It looks like this formula does not work as it was expected

:recommended is supposed to generate ```--without-botan``` option. 
Not sure what would happen if it is overwritetn with ```--with-botan```  but you can see that botan is not installed and rnp build fails: https://github.com/rnpgp/homebrew-rnp/actions/runs/9127459830

There may be some clue here https://docs.brew.sh/Formula-Cookbook#check-for-dependencies but I did not understand what this manual says

**Comment by ni4** [comment]
@maxirmx Thanks for the hint! Will fix that to work as expected. They really have a bit confusing manual.

**Comment by ni4** [comment]
@maxirmx I removed optional backend selection as it is not something which is supported in homebrew-core as per documentation.

**Review by maxirmx — APPROVED** [review]
@ni4 , I bumped  actions/cache version

**Pull request merged**
