### PR TITLE
Test formula in Travis CI

### LINKED ISSUE #3: Add Travis build
(Edited by @skalee)

- [x] ~Test that formula passes `brew audit`.~ (extracted to #8)
- [ ] Test that stable version is installable from source.
- [ ] Test that HEAD version is installable from source.

### PR DESCRIPTION
**Pull request by skalee**
Fixes #3.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Looks great. Thanks @skalee !

**Comment by dewyatt** [comment]
What's the purpose of allowing failures on this?

**Comment by skalee** [comment]
@dewyatt Because unstable Rnp master does not mean that formula is unstable.

**Comment by dewyatt** [comment]
@skalee Oops I actually read the matrix wrong, it looked like a single entry that was allowed to fail, which didn't make sense. I see the osx_image section now.

**Comment by skalee** [comment]
@ronaldtse I am not sure if it was intentional, but tests are run on travis-ci.com, not on .org. I am okay with that though.

**Comment by ronaldtse** [comment]
Travis is migrating all .org to .com, so newer enabled repos are all done on .com.

**Pull request merged**
