### PR TITLE
rnp reference updated to 0.16.3

### LINKED ISSUE #30: Update Homebrew for v0.16.3

### LINKED ISSUE #31: Fresh installed rnp on macOS fails
## Description

I freshly installed RNP on my macOS with brew as described in [installation](https://github.com/rnpgp/rnp/blob/main/docs/installation.adoc#on-macos-using-homebrew). After the installation I'm not able to run RNP as there's a library missing.

## Environment

macOS Ventura 13.3

```
$ brew info rnp
==> rnpgp/rnp/rnp: stable 0.15.2 (bottled), HEAD
High-performance OpenPGP command-line tools and library
https://github.com/rnpgp/rnp
/usr/local/Cellar/rnp/0.15.2 (16 files, 2.7MB) *
  Poured from bottle on 2023-04-13 at 08:14:34
From: https://github.com/rnpgp/homebrew-rnp/blob/HEAD/Formula/rnp.rb
==> Dependencies
Build: cmake ✔
Required: botan ✔, json-c ✔
==> Options
--HEAD
	Install HEAD version
```

## Steps to Reproduce

1. Get a freshly installed macOS with homebrew.
2. Follow the [instructions](https://github.com/rnpgp/rnp/blob/main/docs/installation.adoc#on-macos-using-homebrew).
3. Run `rnp --version`

## Expected Behavior

RNP should find the library libbotan and print its version.

## Actual Behavior

```
$ rnp --version
dyld[16402]: Library not loaded: /usr/local/opt/botan/lib/libbotan-2.18.dylib
  Referenced from: <7405531A-B97F-34D4-B9BE-4EB91C570555> /usr/local/Cellar/rnp/0.15.2/bin/rnp
  Reason: tried: '/usr/local/opt/botan/lib/libbotan-2.18.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/botan/lib/libbotan-2.18.dylib' (no such file), '/usr/local/opt/botan/lib/libbotan-2.18.dylib' (no such file), '/usr/local/lib/libbotan-2.18.dylib' (no such file), '/usr/lib/libbotan-2.18.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/botan/2.19.3/lib/libbotan-2.18.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/botan/2.19.3/lib/libbotan-2.18.dylib' (no such file), '/usr/local/Cellar/botan/2.19.3/lib/libbotan-2.18.dylib' (no such file), '/usr/local/lib/libbotan-2.18.dylib' (no such file), '/usr/lib/libbotan-2.18.dylib' (no such file, not in dyld cache)
```

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Curerent failure:

```
==> Running TapSyntax#run!
[10](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:11)
==> brew style rnpgp/rnp
[11](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:12)
==> brew readall --aliases rnpgp/rnp
[12](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:13)
==> brew audit --tap=rnpgp/rnp
[13](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:14)
==> FAILED
[14](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:15)
Full audit --tap=rnpgp/rnp output
[15](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:16)
  rnpgp/rnp/rnp:
[16](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:17)
    * fully scope test shell_output calls, e.g. shell_output "#{bin}/rnp"
[17](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:18)
  Error: fully scope test shell_output calls, e.g. shell_output "#{bin}/rnp"
[18](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:19)
  Error: 1 problem in 1 formula detected
[19](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:21)
Error: 1 failed step!
[20](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:22)
brew audit --tap=rnpgp/rnp
[21](https://github.com/rnpgp/homebrew-rnp/actions/runs/4693384831/jobs/8320297136?pr=32#step:7:23)
```

**Comment by maxirmx** [comment]
I believe we should not publish bottle. It will contain rnp binary with direct reference to specific version of botan
If botan is updated in homebrew rnp bottle will refer to outdated botan library version as we see in #31

**Comment by ronaldtse** [comment]
@maxirmx can't we specify a bottle dependency on the particular botan version? The benefit of the bottle is to allow people not to go through compilation, and it is an important benefit.

**Comment by maxirmx** [comment]
> @maxirmx can't we specify a bottle dependency on the particular botan version? The benefit of the bottle is to allow people not to go through compilation, and it is an important benefit.

My understanding is that botan provides a formula to install only the latest version. Thus, even if we specify a dependency on some other version of botan, it will not be installed.

I believe we can 
- make a formula that uses bottle if botan version matches and builds from source if botan version does not match 
- link botan as static library in homebrew formula. It will eliminate run-time dependency
- link rnp agains more generic reference (botan-2.dylib instead of botan-2.19.dylib).  This will probably work but it is something to be done in core rnp build scripts 

Also I guess we will need several bottles to make it effective. Botan provides seven:
-   arm64_ventura
-   arm64_monterey
-   arm64_big_sur
-   ventura
-   monterey
-   big_sur
-   catalina

This may require cross-compile options that will also go to core rnp build scripts

I suggest we release a simple fix first since keeping the bottle does not look like a one-liner fix

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Agree that a simple fix is desired here. We can fix the bottle after. Thanks.

**Comment by ronaldtse** [comment]
@maxirmx Feel free to merge when ready, thanks.

**Review by ribose-jeffreylau — APPROVED** [review]

**Comment by maxirmx** [comment]
Needs to be  recreated to apply pr-pull workflow

**Pull request merged**
