### PR TITLE
Update for the CMake conversion.

### PR DESCRIPTION
**Pull request by dewyatt**
If https://github.com/riboseinc/rnp/pull/685 is merged.

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
This is so much, so much cleaner. 👍

**Comment by dewyatt** [comment]
Made a small update here (and addressed the Hound issues).

**Comment by ronaldtse** [comment]
@dewyatt looks good to me. While you're at it, could you help update the "description" part to use some better text, and remove the reference to GnuPG? 😉 Thanks!

**Comment by dewyatt** [comment]
@ronaldtse Is this description OK? It's also what we're using for rnp packaging ([here](https://github.com/riboseinc/rnp/blob/5a96673c95dbf4074d7411ada764ca32840f497c/cmake/info.cmake#L33)) so let me know if you would prefer something else.

**Comment by ronaldtse** [comment]
Could we add something about aiming for "high performance"? It'll be good enough. Thanks!

**Comment by dewyatt** [comment]
Can we get this one merged?

**Comment by ronaldtse** [comment]
Done.

**Pull request merged**
